af = ArrayFire{OpenCL}()

afArr = array(af, [[1, 2] [3, 4]])
result = afArr .< array(af, [[2, 2] [2, 2]])
println(host(result))
result = afArr .<= array(af, [[2, 2] [2, 2]])
println(host(result))
result = afArr == array(af, [[2, 2] [2, 2]])
println(host(result))
result = afArr != array(af, [[2, 2] [2, 2]])
println(host(result))
result = afArr .> array(af, [[2, 2] [2, 2]])
println(host(result))
result = afArr .>= 2
println(host(result))

afArr = array(af, [[0, 1] [2, 0]])
result = and(afArr, array(af, [[true, false] [true, false]]))
println(host(result))
result = or(afArr, array(af, [[true, false] [true, false]]))
println(host(result))
